name: Build release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PROTOS_SUBMODULE_TOKEN }}
          submodules: true
      - name: create version
        run: |
          echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - name: set up java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
      - name: install keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.keystore }}
        run: |
          KEYSTORE=$RUNNER_TEMP/keystore.jks
          echo -n "$KEYSTORE_BASE64" | base64 --decode > $KEYSTORE
          echo "KEYSTORE=$KEYSTORE" >> $GITHUB_ENV
      - name: create aar
        run: |
          ./gradlew clean
          ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: publish to maven central
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.MAVEN_SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_SIGNING_KEY_PASSWORD }}
          SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$VERSION" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$VERSION" \
            --generate-notes
      - name: attach aar to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$VERSION" app/build/outputs/aar/nosy-logger-release.aar
