name: Build release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: resursive
      - name: set up java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
      - name: install keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.keystore }}
        run: |
          KEYSTORE=$RUNNER_TEMP/keystore.jks
          echo -n "$KEYSTORE_BASE64" | base64 --decode > $KEYSTORE
          echo "KEYSTORE=$KEYSTORE" >> $GITHUB_ENV
      - name: create aar
        run: |
          ./gradlew clean
          ./gradlew generateReleaseProto
          ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: publish to maven central
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.MAVEN_SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.MAVEN_SIGNING_KEY_PASSWORD }}
          SIGNING_KEY: ${{ secrets.MAVEN_SIGNING_KEY }}
